apiVersion: apps/v1
kind: Deployment
metadata:
  name: contextionary
  labels:
    name: contextionary
    app: contextionary
spec:
  replicas: {{ .Values.contextionary.replicas }}
  selector:
    matchLabels:
      app: contextionary
  template:
    metadata:
      labels:
        app: contextionary
    spec:
      containers:
      - name: contextionary
        image: {{ .Values.contextionary.registry }}/{{ .Values.contextionary.repo }}:{{ .Values.contextionary.tag }}
        env:
          - name: OCCURRENCE_WEIGHT_LINEAR_FACTOR
            value: {{ .Values.contextionary.envconfig.occurrence_weight_linear_factor | quote }}
          - name: EXTENSIONS_STORAGE_MODE
            value: {{ .Values.contextionary.envconfig.extensions_storage_mode }}
          - name: EXTENSIONS_STORAGE_ORIGIN
            value: http://{{ .Values.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
          - name: NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE
            value: {{ .Values.contextionary.envconfig.neighbor_occurrence_ignore_percentile | quote }}
          - name: ENABLE_COMPOUND_SPLITTING
            value: {{ .Values.contextionary.envconfig.enable_compound_splitting | quote }}
        resources: 
{{ toYaml .Values.contextionary.resources | indent 10 }}
