apiVersion: apps/v1
kind: Deployment
metadata:
  name: contextionary
  labels:
    name: contextionary
    app: contextionary
spec:
  selector:
    matchLabels:
      app: contextionary
  template:
    metadata:
      labels:
        app: contextionary
    spec:
      containers:
      - name: contextionary
        image: {{ .Values.contextionary.registry }}/{{ .Values.contextionary.repo }}:{{ .Values.contextionary.tag }}
        env:
          - name: SCHEMA_PROVIDER_URL
            value: http://{{ .Values.etcd.fullnameOverride }}:2379
        resources:
{{ toYaml .Values.contextionary.resources | indent 10 }}
