language: minimal
before_install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh
- chmod 700 get_helm.sh
- sudo ./get_helm.sh
- helm init --client-only
install: true
script:
- "./release.sh"

deploy:
  provider: releases
  api_key:
    secure: jIEQUax2+2rXU61GpBN/BLYDrOrAOIOPEijixOHjY+5O1cRwzpUIgLItMED+es8Y+0XZxFKAtYLGvWWHvY9T4jOiqHRJS/uM5Bj1CGbFgZwL+zw8W3hylboC36Sc75p24QnrhGt+XJ9eWOd+BFSZvCm0Di+UMmoigKVMmeGsox9f5wCdEffd8hYySLIV6UnfDtN1dY7BIlo1Gr9sNF1ksLJQEXbxXttMeaQ6QepHn/lX9f7Ou9888Jcv1akdLMxC26mpH4eSGb4w1CRuIb9uwQRrdOR/PCrw9oYL3QOc7APrHpZXPrTV80J9qhs6Fo1fkG6B/6z8bci2hSJjHvA0PJBB1rW+TLNB/Dln6MfR6LMEXd5jhoiuChJeezwBlU+ag3DSqkUPLAT81Dqrrni237M1URPyS5Cslb4nDeiQkgqHAcCztE7ykQaLkSbBdokPm5L5fx8jo55jnWi6rcIK0f+q5IIWUoOmMCq8Jmv0pik0qWIdPRioQQJ7Q7oW7OlI1VTNvpGi56n4/zOZds6iVE/X+nr2zRlBTp2t2hrMZxWV2IivVvryZz5QWW6jJnUoQhIBPBJcFqNq+zjZC/Bxs+K6hQlakxPkxR+6Xxt+SFCQfuXwtMN032lW3KSeOEqGdgdMmoEYMjBjntI8vx8g0YIQz+sZY+a2WvFheI1qMKg=
  file: weaviate/weaviate.tgz
  skip_cleanup: true
  draft: true
  on:
    repo: semi-technologies/weaviate-helm-gcp-marketplace
    tags: true
