dependencies:
  - name: elasticsearch
    version: 7.4.0
    repository: 'https://helm.elastic.co'
    alias: esvector

  - name: etcd
    version: 4.8.2
    repository: 'https://charts.bitnami.com/bitnami'
    alias: etcd
    condition: etcd.deploy

