# GCP Marketplace specific
#
marketplace:
  ubbagentImage: replace-me-via-schema-yaml
  reportingSecretName: replace-me-via-schema-yaml
  serviceName: replace-me-via-values.yaml
  metricName: replace-me-via-values.yaml
  planSelectionEnum: replace-me-via-schema-yaml # see _helpers.tpl for how this is used

# Related to the weaviate image
image:
  # registry where weaviate image is stored
  registry: docker.io
  # Tag of weaviate image to deploy
  # Note: We strongly recommend you overwrite this value in your own values.yaml.
  # Otherwise a mere upgrade of the chart could lead to an unexpected upgrade
  # of weaviate. In accordance with Infra-as-code, you should pin this value
  # down and only change it if you explicitly want to upgrade the Weaviate
  # version.
  tag: 1.0.0
  repo: semitechnologies/weaviate

# manually scale horizontal replicas of weaviate.
# Also note: https://github.com/semi-technologies/weaviate/issues/725
replicas: 1
resources:
  requests:
    cpu: '500m'
    memory: '300Mi'
  limits:
    cpu: '1000m'
    memory: '1Gi'
storage:
  size: 32Gi

# The service controls how weaviate is exposed to the outside world. If you
# don't want a public load balancer, you can also choose 'ClusterIP' to make
# weaviate only accessible within your cluster.
service:
  name: weaviate
  type: LoadBalancer

# Weaviate Config
#
# The following settings allow you to customize Weaviate to your needs, for
# example set authentication and authorization optins. See weaviate docs
# (https://www.semi.technology/documentation/weaviate/current/) for all
# configuration.
authentication:
  anonymous_access:
    enabled: true
authorization:
  admin_list:
    enabled: false
query_defaults:
  limit: 100
debug: false
telemetry:
  disabled: true
vector_index:
  # must be enabled since 0.20.x, there is no non-vector alternative anymore
  enabled: true

modules:
  default_vectorizer_module: text2vec-contextionary
  text2vec-contextionary:
    enabled: true

# It is also possible to configure authentication and authorization through a custom configmap
# The authorization and authentication values defined in values.yaml will be ignored when defining a custom config map.
custom_config_map:
  enabled: false
  name: 'custom-config'

# The collector proxy collects meta data over the requests.
# It deploys a second service that, if used, will capture meta data over the incoming requests.
# The collected data may be used to optimize the software or detect mallicious attacks.
collector_proxy:
  enabled: false
  tag: latest
  weaviate_enterprise_token: ''
  weaviate_enterprise_project: ''
  service:
    name: 'usage-proxy'
    port: 80
    type: LoadBalancer

# Kubernetes-specific configuration for the contextionary deployment
contextionary:
  fullnameOverride: contextionary
  tag: en0.16.0-v0.4.21
  repo: semitechnologies/contextionary
  registry: docker.io
  replicas: 1
  envconfig:
    occurrence_weight_linear_factor: 0.75
    neighbor_occurrence_ignore_percentile: 5
    enable_compound_splitting: false
    extensions_storage_mode: weaviate
  resources:
    requests:
      cpu: '500m'
      memory: '500Mi'
    limits:
      cpu: '1000m'
      memory: '5000Mi'
